### PR TITLE
169 need an option to expand allof blocks for proper semantical difference

### LINKED ISSUE #169: Need an option to expand "allOf" blocks for proper semantical difference
**Describe the bug**
"allOf" construct from JSON-schema is a recommended and widely used approach to combine schemas in OpenAPI specs and avoid copy-pasting. Sometimes we refactor specs and replace plain schemas with full equivalents using "allOf". As far as I can see OASDIFF always detects it as a breaking change, even if underlying schemas are fully equivalent.

**To Reproduce**
1. Run `oasdiff  -format text -base oasdiff-test1.yml -revision oasdiff-test12.yml
2. With [oasdiff-allof-test.zip](https://github.com/Tufin/oasdiff/files/10369855/oasdiff-allof-test.zip)
3. Receive the following result:

<pre>
### Modified Endpoints: 1
-------------------------
GET /test
- Responses changed
  - Modified response: 200
    - Content changed
      - Modified media type: application/json
        - Schema changed
          - Property 'AllOf' changed
            - 2 schemas added
          - Type changed from 'object' to ''
          - Properties changed
            - Deleted property: description
            - Deleted property: name         
 </pre>

**Expected behavior**
I expect to have a command line option to get rid of "allOf" and convert them to equivalent inline schemas.
So that two semantically equivalent specs (like in my example) will not be considered as different:

<pre>
### Modified Endpoints: 0
</pre>

#154 could be about the same thing

### PR DESCRIPTION
**Pull request by reuvenharrison**

### CODE REVIEW

**Comment by fenollp** [comment]
What do you think about upstreaming this to kin-openapi?

I remember at least one other issue over there asking for a flatten operation (that'd behave a bit differently).

**Comment by reuvenharrison** [comment]
Hi @fenollp,
I think that's a great idea.
Please let me know if I can help.
Thanks,
Reuven

**Comment by fenollp** [comment]
Well I'm still working on making all iteration operations deterministic then I'd like to impl a visitor and would love to have this on top. 

But we can definitely have a func do this right now and add determinism afterwards. 
Feel free to open a PR over there

**Comment by reuvenharrison** [comment]
Sorry @fenollp but I don't understand your suggestion about opening a PR, what did you have in mind to include in this PR?

**Comment by fenollp** [comment]
I am suggesting to move this flatten code to upstream kin-openapi.

**Comment by reuvenharrison** [comment]
Transitioning this PR to https://github.com/oasdiff/kin-openapi

**Pull request closed without merging**
