### PR TITLE
Fix get_machine In Install Script

### LINKED ISSUE #565: Checksums do not match while using install script.
**Describe the bug**
install.sh returns `Checksums do not match` while building docker image on Linux_x86_64 machine.

**To Reproduce**
1. run curl -fsSL https://raw.githubusercontent.com/tufin/oasdiff/main/install.sh | sh on Linux_x86_64

**Expected behavior**
It should install without error

**Desktop (please complete the following information):**
 - Linux_x86_64

**Additional context**

I have following Dockerfile
`FROM ubuntu:16.04

RUN apt-get update && apt-get install -y curl
RUN curl -fsSL https://raw.githubusercontent.com/tufin/oasdiff/main/install.sh | sh
`
I'm building it using `docker build -t package_name .`, it works properly on MacOs, but while building it on Linux_x86_64 arch it returns following log

`
 > [3/3] RUN curl -fsSL https://raw.githubusercontent.com/tufin/oasdiff/main/install.sh | sh:
#6 1.472 sh: 130: [: linux: unexpected operator
#6 1.477 Temporary directory is /tmp/tmp.IG25IOBuQ3
#6 1.477 Downloading https://github.com/Tufin/oasdiff/releases/download/v1.10.17/oasdiff_1.10.17_linux_x86_64.tar.gz
#6 2.043 Validating checksum
#6 2.044 https://github.com/Tufin/oasdiff/releases/download/v1.10.17/checksums.txt
#6 3.298 Checksums do not match
` 

From what I see, this architecture should be supported, however it is not listed in [checksums.txt](https://github.com/Tufin/oasdiff/releases/download/v1.10.17/checksums.txt)
`
d28dbecd45fd657a0c5814626686155addb9490ab8db07160ccbff2745289222  oasdiff_1.10.17_darwin_all.tar.gz
0fcaa93d61e74c8e4b417a545cbb478d68c50a6bbe732d56f92ee14a1c6577d8  oasdiff_1.10.17_linux_amd64.apk
1ba966cc5e36c141328e235087dca407b7e0a24c4e99b9619f50deedd6193a19  oasdiff_1.10.17_linux_amd64.deb
011dd531c0b0435899b33774d5d96e6a3baa5a7177db3bef408e6929c6abdf17  oasdiff_1.10.17_linux_amd64.rpm
718a3629f66f1c04f6e4e6a61aa0b042621a6b35e8d80fdc87c5d40e3f0e949e  oasdiff_1.10.17_linux_amd64.tar.gz
da0944918aa4b1728cf15927451f5ae1f407aff1888208e6878324f6375f9139  oasdiff_1.10.17_linux_arm64.apk
a1eb5034d1f324bfd750f9aa7113c458b66253e5914bb18100e59cfc945c2399  oasdiff_1.10.17_linux_arm64.deb
d55822e91cee356bc7d35e485fb34d7165e8905514c3f189793d49dff2ee69c2  oasdiff_1.10.17_linux_arm64.rpm
63d115f541be901337fe3217e2a07ed3dfde5b0ce33aaf152ed9880256b5513e  oasdiff_1.10.17_linux_arm64.tar.gz
9e234003d4fc113a3981cda557eb4745dcaaa663e45194eb6081c9135b77aa7b  oasdiff_1.10.17_windows_amd64.tar.gz
4923df8ed0d367bde22d466eb0cb9a0c6f8a378b88e913fbb8d3541d8c27097d  oasdiff_1.10.17_windows_arm64.tar.gz
`

Alternatively, is there any way to use your docker image with disabled TLS, or to configure TLS for self-signed certificate?

### PR DESCRIPTION
**Pull request by mahirpiy**
Fixes https://github.com/Tufin/oasdiff/issues/565 using the change suggested by @scastria (https://github.com/Tufin/oasdiff/issues/565#issuecomment-2215654139)

### CODE REVIEW

**Review by reuvenharrison — APPROVED** [review]

**Comment by reuvenharrison** [comment]
Thanks for your contribution :-)

**Comment by mahirpiy** [comment]
@reuvenharrison do you think this could be released soon? currently hard blocks my team on something, would love to get it over the line

**Comment by reuvenharrison** [comment]
Hi @mahirpiy,
I just released it: https://github.com/Tufin/oasdiff/releases/tag/v1.10.20
It would be great if you could share how you are using it.
Reuven

**Comment by mahirpiy** [comment]
@reuvenharrison thank you!! 

my team uses the install script in our CI runner to detect any changes made to our api contracts. we use the generated diff to send a message in an `api-changes` slack channel, so our client engineers are aware of changes. its part of a bigger api-compatibility overhaul that has our mobile engineers creating data classes directly from the open api yaml. thanks for all you do!

**Pull request merged**
