### PR TITLE
refactor: move output code into formatters, add junit and githubactions

### PR DESCRIPTION
**Pull request by PhilippHeuer**
Creating this as a draft / suggestion for feedback to see if this approach works for you.

### Changes Proposed
- move all code that deals with rendering output into `formatters`
- strip ansi escape codes in all data serialization formats (json, yaml, junit, ...) - i would only include these in `text` output
- add junit format (breaking-changes)
- add githubactions format (breaking-changes)

### Incomplete
- have the `checks` command return a list of all checks - maybe add a filter param for optional checks?
- complete the list of checks

### Additional Information
- a list of all rules would be useful (for junit/sarif) - including key, description - i added one as example in https://github.com/PhilippHeuer/oasdiff/blob/3a27bf871c6f9b3d07b86d3b3d56f2c0772e9899/checker/default_checks.go#L159-L169
- supporting the sarif format would require the file and location for the source - not sure if this will be possible (maybe if the files don't contain references), added the fields optionally for now in case this will become possible at some point in the future
- the method i used to strip the ansi escape codes is more of a hack than a solution

### CODE REVIEW

**Comment by jbergstroem** [comment]
It would be awesome if the githubactions reporter also added a count of error/warn/notice to variables (`echo ERROR_COUNT=5 >> $GITHUB_ENV`). That way the github action can make them available to github action users and you can use it in logic for further steps.

**Comment by PhilippHeuer** [comment]
> It would be awesome if the githubactions reporter also added a count of error/warn/notice to variables (`echo ERROR_COUNT=5 >> $GITHUB_ENV`). That way the github action can make them available to github action users and you can use it in logic for further steps.

Good idea, i'll add a commit to set the values as job output parameters (instead of env) - this should be better to avoid potential name conflicts with other env variables.

**Comment by jbergstroem** [comment]
> Good idea, i'll add a commit to set the values as job output parameters (instead of env) - this should be better to avoid potential name conflicts with other env variables.

Yes, output is superior here. Thanks for that!

**Comment by reuvenharrison** [comment]
Hi @PhilippHeuer,
Please let me know if you need help to finish this PR.
FYI, I am about to merge another PR that may require some manual merging into this one.
Reuven

**Comment by PhilippHeuer** [comment]
I'll take a look today to push my latest changes + resolve the conflicts.

**Comment by PhilippHeuer** [comment]
**Changes**

- completes the list of all rules
- all checker functions now have a `Check` suffix
- all rule-id's are now constants and referenced in the rule list (/checks list)
- `oasdiff checks` now supports `lang`, `severity`, `tags` and `required` for filtering
    - oasdiff checks --severity error # list all checks with severity error
    - oasdiff checks --tags body # list all checks related to the body
    - oasdiff checks --required false # list all optional checks
- All rule's come with a `<ruleId>-description` localization key, that we can use to describe what the rule in general (not the specific error) - writing this is out-of-scope for this PR.

I think we shouldn't add any other changes to this PR if possible, as it's already quite big / hard to review.

**Checkers**

There are a lot minor changes in the `Checkers` to unify the rule-id's that were not very consistent as i needed to reference them in the checks list. (public const, camelCase, Id suffix)
Does this style work for you or would you prefer something else?

**Idea for a Future PRs**

1: use the new checks list in the junit report

2: `oasdiff checks --required false` includes two more items than the old `oasdiff checks` because one Checker function can return multiple rule-id's.
I was thinking that we could always run all Checkers and allow users to include optional / exclude required result items based on the rule-id's for more fine-grained control.

**Review by reuvenharrison — COMMENTED** [review]
I'm reviewing...

**Review by reuvenharrison — APPROVED** [review]
Hi @PhilippHeuer,
Thanks for your valuable contribution.
The new formatters look great.
From my perspective it's ready to merge.
Reuven

**Pull request merged**
